//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThisWarOfMine.Infrastructure.Telegram.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThisWarOfMine.Infrastructure.Telegram.Resources.Messages.Responses", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to game.
        /// </summary>
        internal static string BackToGame {
            get {
                return ResourceManager.GetString("BackToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language was updated.
        /// </summary>
        internal static string LanguageWasUpdated {
            get {
                return ResourceManager.GetString("LanguageWasUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no translation for this language.
        /// </summary>
        internal static string NoTranslationForThisLanguage {
            get {
                return ResourceManager.GetString("NoTranslationForThisLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no command to complete your request.
        /// </summary>
        internal static string NotRecognizedMessageCommand {
            get {
                return ResourceManager.GetString("NotRecognizedMessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The story number is invalid or has an incorrect format.
        /// </summary>
        internal static string NotValidStoryNumber {
            get {
                return ResourceManager.GetString("NotValidStoryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsHeader {
            get {
                return ResourceManager.GetString("OptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The story is not found.
        /// </summary>
        internal static string StoryNotFound {
            get {
                return ResourceManager.GetString("StoryNotFound", resourceCulture);
            }
        }
    }
}
